
/**
 * 播放视频
 * */
@Entry
@Component
struct TestPlayVideoPage {
  @State videoSrc: Resource = $rawfile('1.mp4')
  @State previewUri: Resource = $r('app.media.app_icon') //预览封面
  @State curRate : PlaybackSpeed = PlaybackSpeed.Speed_Forward_1_00_X   //1倍数播放
  @State isAutoPlay: boolean = false   //是否自动播放
  @State showControls: boolean = true  //是否显示视频控制栏
  controller: VideoController = new VideoController()

  build() {
    Row() {
      Column() {
        Video({
          src: this.videoSrc,
          previewUri: this.previewUri,
          currentProgressRate: this.curRate,
          controller: this.controller
        })
          .width('100%')
          .height(600)
          .autoPlay(this.isAutoPlay)
          .controls(this.showControls)
          .onStart(()=>{
            console.log('onStart')
          })
          .onPause(()=>{
            console.log('onPause')
          })
          .onFinish(()=>{
            console.log('onFinish')
          })
          .onError(()=>{
            console.log('onError')
          })
        .onPrepared((e?: DurationObject)=>{ //获取总的播放时长
          if (e != undefined) {
            console.log('onPrepared is'  + e.duration)
          }
        })
        .onSeeking((e?: TimeObject) => { //拖拽到哪里的监听，比如6，7，8，9秒的为位置
           console.log('onSeeking is ' + e.time)
        })

        Row(){
          Button('开始播放').onClick(()=>{
            this.controller.start()//这里是开始播放
          })
            .margin(5)
          Button('暂停播放').onClick(()=>{
            this.controller.pause() //这里是暂停播放
          }).margin(5)
          Button('停止播放').onClick(()=>{
            this.controller.stop() //这是停止播放
          }).margin(5)
          Button('跳到10s位置').onClick(()=>{
            this.controller.setCurrentTime(10, SeekMode.Accurate) //定位到某个位置
          }).margin(5)
        }

        Row(){
          Button('切换视频').onClick(()=>{
            this.videoSrc = $rawfile('2.mp4') //切换到2这个视频进行播放
          }).margin(5)

          Button('切换预览封面').onClick(()=>{
            this.previewUri = $r('app.media.phone')  //切换预览的封面
          }).margin(5)

          Button('是否显示视频控制栏').onClick(()=>{
            this.showControls = !this.showControls //切换是否显示视频控制栏
          }).margin(5)
        }

        Row(){
          Button('0.75倍数').onClick(()=>{
            this.curRate = PlaybackSpeed.Speed_Forward_0_75_X;
          }).margin(5)
          Button('1倍数').onClick(()=>{
            this.curRate = PlaybackSpeed.Speed_Forward_1_00_X;
          }).margin(5)
          Button('2倍数').onClick(()=>{
            this.curRate = PlaybackSpeed.Speed_Forward_2_00_X;
          }).margin(5)
        }

      }
      .width('100%')
    }
    .height('100%')
  }
}
interface DurationObject{
  duration: number;
}

interface TimeObject{
  time: number;
}