
/**
 * 各种进度条
 * */
@Entry
@Component
struct TestProgressBarPage {
  @State message: string = '各种进度条'
  @State i : number = 50
  build() {
    Row() {
      Column() {
        Text(this.message)
          .fontSize(20)
          .fontWeight(FontWeight.Bold)

        //进度条
        Progress({value: 24, total: 100, type: ProgressType.Linear})
          .margin({top: 30})
        //日蚀
        Progress({value: 24, total: 100, type: ProgressType. Eclipse})
          .margin({top: 30})

        //环
        Progress({value: 24, total: 100, type: ProgressType. Ring})
          .margin({top: 30})

        //分度环
        Progress({value: this.i, total: 150, type: ProgressType.ScaleRing}) //分度环
          .color(Color.Blue) //进度条的颜色
          .value(this.i)
          .width(50)
          .margin({top: 30})
          .style({strokeWidth: 15, scaleCount: 15, scaleWidth: 5}) // scaleCount 刻度的总数，scaleWidth 刻度的宽度

        //胶囊样式
        Progress({value: 20, total:150, type: ProgressType.Capsule})
          .width(100)
          .height(50)
          .margin({top: 30})
      }
      .width('100%')
    }
    .height('100%')
  }
}